### ISSUE TITLE
s3p sync failing with "something's not right"

### ISSUE THREAD

**Issue by siebrand** [generalui/s3p#82]
nodejs version: 16.20.0
s3p version: 3.4.6

I'm trying to sync a structure from a source bucket to a target bucket, but this consistently fails with multiple messages "_**something's not right**_". As far as I can tell, I'm only using supposed characters in the prefixes and object names.

The failing command is with a prefix, as I've tried to reduce the scope of the problem -- didn't really work. The result is the same without using a prefix. "s3p ls" on the source bucket and target bucket work as expected; it results in a file list.

Attachments:

- [objectlist.zip](https://github.com/generalui/s3p/files/11452390/objectlist.zip) (at the time of testing, source and target buckets were in sync; done with "aws s3 sync")
- [command_success.txt](https://github.com/generalui/s3p/files/11452391/command_success.txt)
- [command_fail.txt](https://github.com/generalui/s3p/files/11452392/command_fail.txt)

**Comment by shanebdavis** [comment]
Hi @siebrand. It's been a crazy year, so I'm only just now seeing your bug report. Excellent job with your details. It was exactly what I needed to find and fix the bug. It should be patched in v3.4.9. Do you still have access to those buckets? I'd love to hear if it actually fixes your issue in the real world. 

However, I imagine I'm a bit late to solve your issue at the time, but I greatly appreciate the concise bug report so that it might help you or others in the future.

Thank you!

**Comment by siebrand** [comment]
Just a quick update from my side: This is still on my list to test.

**Comment by siebrand** [comment]
Sorry to take a while before reporting back. This issue has been resolved.

**Comment by shanebdavis** [comment]
Great! Thank you for reporting back.
